### ISSUE TITLE
错误: 程序包com.huawei.hms.activity等不存在

### ISSUE THREAD

**Issue by 1512751361** [Aicxz/react-native-huawei-push#1]
![image](https://user-images.githubusercontent.com/24776858/59257336-5316c780-8c68-11e9-811b-fba3087c6252.png)
![image](https://user-images.githubusercontent.com/24776858/59257364-632ea700-8c68-11e9-87d2-3d1be75a7c25.png)
android的工程里找不到对应的这些程序包
import com.huawei.hms.activity.BridgeActivity;
import com.huawei.hms.api.ConnectionResult;
import com.huawei.hms.api.HuaweiApiAvailability;
import com.huawei.hms.api.HuaweiApiClient;

**Comment by Aicxz** [comment]
已修复，请更新到v1.1.0版本
